# Permalinks
permalink:           pretty

# Setup
title:               SELinux Game
tagline:             'Learn SELinux By Doing'
description:         'Solve SELinux puzzles to learn and demonstrate your SELinux skillz'
url:                 http://selinuxgame.org
baseurl:             'http://selinuxgame.org'
paginate:            1

# About/contact
author:
  name:              Dennis Kliban and Brian Bouterse
  url:               https://twitter.com/selinux
  email:             none@example.com

# Collections
collections:
  scenarios:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: scenarios
    values:
      layout: scenario

# Custom vars
version:             1.0.0
