# Permalinks
permalink:           pretty

# Setup
title:               SELinux Game
tagline:             'Learn SELinux By Doing'
description:         'Solve SELinux puzzles to learn and demonstrate your SELinux skillz'
url:                 http://selinuxgame.org
baseurl:             'http://selinuxgame.org'

# About/contact
author:
  name:              Dennis Kliban and Brian Bouterse
  url:               https://twitter.com/selinux
  email:             none@example.com

# Collections
collections:
  scenarios:
    output: true
  tutorials:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: scenarios
    values:
      layout: scenario
  - scope:
      path: ""
      type: tutorials
    values:
      layout: tutorials

# Custom vars
version:             1.1.0a1

# box-add-urls: http://example.com/
